### ISSUE TITLE
Color legend

### ISSUE THREAD

**Issue by pwellner** [openiaq/map-website#1]
Add legend on bottom right showing relationship between color and CO2ppm.  Default color scale to be conventional green-orange-red scale, but toggle button will allow switching back to current color scale for color-blind users.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a legend component to show the relationship between color and CO2ppm. Implemented a toggle button to switch between the conventional green-orange-red scale and the current color scale for color-blind users. Modified the MapComponent to include the legend and updated the color functions.

You can review changes in this commit: https://github.com/lkilu6456546/openiaq-map-website-1/commit/070d3890114c37904d62b66a25294061b8c516b1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by pwellner** [comment]
Closed by branch feat/issue-1/color-scale
